### ISSUE TITLE
Asp.Net MVC 4 Async controllers

### ISSUE THREAD

**Issue by AnthonySteele** [SparkViewEngine/spark#25]
Asp.Net MVC 4 in VS2012 allows controller action to methods return async Task<ActionrResult> instead of ActionResult. Spark appears to not support these.

As per this question https://groups.google.com/forum/?fromgroups#!topic/spark-dev/eyIFm6mnBcE

**Comment by bounav** [comment]
I'm closing down this story. Spark works with async Task<ActionResult> in ASP.NET 5.
