### ISSUE TITLE
Can't resolve "~/" inside html comments

### ISSUE THREAD

**Issue by scott-xu** [SparkViewEngine/spark#42]
consider this piece of code:

``` html
<!--[if lt IE 9]>
  <script src="~/Scripts/html5shiv.js"></script>
  <script src="~/Scripts/respond.min.js"></script>
<![endif]-->
```

The "~/" can't be resolved

**Comment by bounav** [comment]
Would the such `~/...` URLs be resolved with any _other_ view engine?

As far as I understand spark (and Razor), those URLs would be left "as is" by the view engine.
If you wan to _resolve_ something you need to use the relevant placeholder e.g. ${something} to tell the view engine to _output_ something.

I'm going to close this issue.

**Comment by scott-xu** [comment]
Just checked, yes Razor will keep it as is.
