### ISSUE TITLE
1.8.0.0.nupkg has lib/net45 with old version

### ISSUE THREAD

**Issue by maxild** [SparkViewEngine/spark#54]
Install-Package Spark -version 1.8.0.0

Seems to put Spark.dll, version 1.7.0.0 in lib/NET45, and this causes assembly resolving to error, when using Spark.Web.Mvc4 package at the same time... 

![image](https://cloud.githubusercontent.com/assets/46108/6391452/9f3712bc-bdb6-11e4-8c44-26883e9252bc.png)

lib/NET4 btw is ok

![image](https://cloud.githubusercontent.com/assets/46108/6391462/ae7c80d6-bdb6-11e4-88d7-9389aa2c4d3a.png)

**Comment by ChrisPelatari** [comment]
This has carried over to Spark.Web.Mvc5. 

Also the dependency on WebActivator should be WebActivatorEx. 

My current workaround is to use version 1.7.5.3 with Install-Package and -IgnoreDependencies for .net 4.5+

**Comment by RobertTheGrey** [comment]
Hey guys - so sorry about this. I somehow also missed @maxild's initial notification on this - really sorry.

Will release a new nuget this weekend

**Comment by RobertTheGrey** [comment]
I believe this is all fixed in v1.8.1.0 - please let me know if you have any trouble

**Comment by ChrisPelatari** [comment]
Confirmed working! Thanks @RobertTheGrey !
