### ISSUE TITLE
The name 'group' does not exist in the current context

### ISSUE THREAD

**Issue by autonomatt** [SparkViewEngine/spark#56]
I have an error I haven't come across before, and I'm stuck on it. I have the following markup in a spark view:

```html
<table each="var group in Model.VariantGroups">
    <p>${group.Key}</p>
</table>
```
This throws the error "The name 'group' does not exist in the current context". 
This is a redesign, so I have an existing view with pretty much the same markup and this works.
I have tried ```<for each="...">``` instead but get the same error.

Any ideas would be much appreciated.

**Comment by RobertTheGrey** [comment]
I wonder if the word `group` is somehow reserved because of a LINQ thing. Can you try rename to `grp` and see if the same error occurs. The syntax looks right to me

**Comment by autonomatt** [comment]
Didn't work. Very odd as I have another view that works.
It's a _Partial.spark just in case that makes a difference. It looks like it's just not processing the each attribute. I'll keep digging...

**Comment by autonomatt** [comment]
Yeah, so I've set the Model.SomethingThatDoesNotExist and it doesn't throw an error on this, so it's definitely not processing this statement for some reason...

**Comment by RobertTheGrey** [comment]
What if you add some arbirtrary `List<string>` to the `Model` like `Model.TestSomeKeys` - does it cycle through those?

**Comment by autonomatt** [comment]
Found the source of the bug. There was an unclosed ```<th>``` element in the head of the table. Suspected something like this, just couldn't see it.

**Comment by RobertTheGrey** [comment]
Ah ok cool - thanks for letting me know. Glad you fixed it.
