### ISSUE TITLE
Problem searching for effective in Observation

### ISSUE THREAD

**Issue by jokkis0** [SparkViewEngine/spark#59]
Hi, 
I trying to search for a observation by effective (DateTime). 
I have tried this:
http://spark.furore.com/fhir/Observation?subject.identifier=12345&effectiveDateTime=2012-09-17
This does not give me any result. 
Could you please help me how the best way is to search for effective(period og dateTime)?

Thanks

**Comment by RobertTheGrey** [comment]
Hi @jokkis0 - I think you've found the incorrect github project. This one is Spark View Engine

**Comment by jokkis0** [comment]
sorry
